### ISSUE TITLE
use crypto/rand for generating high-entropy cryptographic random values

### ISSUE THREAD

**Issue by dmitshur** [hacdias/indielib#9]
https://datatracker.ietf.org/doc/html/rfc7636#section-4.1 defines `code_verifier` to be a "high-entropy cryptographic random STRING", and notes:

> NOTE: The code verifier SHOULD have enough entropy to make it
> impractical to guess the value.  It is RECOMMENDED that the output of
> a **suitable random number generator** be used to create a 32-octet
> sequence.  The octet sequence is then base64url-encoded to produce a
> 43-octet URL safe string to use as the code verifier.

(Emphasis mine.)

The `math/rand` Go package isn't suitable for that purpose; the `crypto/rand` package can be used in its place.

I'll send a PR that fixes this issue in case you find it helpful.

**Comment by hacdias** [comment]
Closed by #11
